### ISSUE TITLE
Missing Training files

### ISSUE THREAD

**Issue by MKCarter** [CDDLeiden/PCMol#1]
Hi,

I am tyring to test my installation by running `python pcmol/generate.py --target P21918` 

However, when I run this it errors stating:

`FileNotFoundError: [Errno 2] No such file or directory: 'data/training/final_dataset/voc_smiles.txt'`

I found a copy of this file from this repo https://github.com/XuhanLiu/DrugEx/blob/master/data/voc_smiles.txt

Upon re-running `python pcmol/generate.py --target P21918`  - another error is found:

`FileNotFoundError: [Errno 2] No such file or directory: 'data/training/final_dataset/train.tsv'`

Would you be able to provide the missing files? 

Many thanks

**Comment by GJPvWesten** [comment]
great that you are running the code! Have you tried looking into the data repository on zenodo : https://zenodo.org/records/10512870?

In addition, I spoke with the main author (currently away on a break) and he will respond asap (likely by Wednesday)

**Comment by andriusbern** [comment]
Thanks for reporting the issue, it has now been solved. Clone the repository again and try re-running the installation script.

**Comment by MKCarter** [comment]
Thanks @andriusbern - the code is now working as expected!
